# Generated by Django 3.1.1 on 2020-09-17 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0005_auto_20200915_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='comment on article...')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('comment_article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.articles')),
                ('comment_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
